Editor text copy - new behavior
benfry/processing4 pull request #100
Opened 2020-05-10 19:40 UTC by urbanskimichal

This is proposal of the feature that I personally miss the most in PDE - copying / cutting all lines.
When no text is selected and one presses **Ctrl+c** (Cmd+c) or **Ctrl+x** (Cmd+x), the whole text in the line on which the caret is, will be coped or cut.
It allows for easy lines duplicating etc.

2020-06-29 16:37 UTC, sampottinger requested changes

2020-06-29 16:37 UTC, sampottinger commented on app/src/processing/app/syntax/JEditTextArea.java
> +  public final void selectLine(final int line)
Hey @urbanskimichal! I think I'm in favor of the change if it isn't confusing to new users (I don't think it would be, it's common behavior for a lot of editors). However, could you say more about why you made this public?

2020-07-01 21:48 UTC, sampottinger commented
Hey there @urbanskimichal! I am doing a integration build so I modified the above to private. It's still ok to change back but wanted to make that edit before bringing this branch into integration.

2020-07-01 21:56 UTC, sampottinger commented
See https://github.com/urbanskimichal/processing4/pull/1

2020-07-07 00:09 UTC, sampottinger commented
This is available on an integration branch at https://github.com/sampottinger/processing4 (`master`) for testing in the context of other open PRs with a community build at https://www.datadrivenempathy.com/processing.

2022-01-11 14:16 UTC, benfry commented
If we can get a rebased version with that change to `private`, I can incorporate this.

2022-01-15 13:54 UTC, urbanskimichal commented
I resolved conflicts, should I do anything else? What does it mean "to private"?

2022-01-15 15:31 UTC, sampottinger commented
I think @benfry wants selectLine to be made into a private method instead of a public method?

2022-01-15 16:36 UTC, merged

2022-01-15 16:40 UTC, benfry commented
All set for beta 4; thanks!

2022-01-17 14:34 UTC, urbanskimichal commented
So the change is included?

2022-01-17 17:07 UTC, benfry commented
It will be in beta 4, the next release.