Support added for pde:// browser protocol
benfry/processing4 pull request #689
Opened 2023-03-18 05:48 UTC by lala-lala-lori

I have added the support of pde:// browser protocol for linux(Fixes: #674 )
which enables the opening of *.pde file from web URLs using the pde:// protocol.

@benfry Could you please review and merge this pull request.
Thanks!

2023-04-04 17:15 UTC, evan-goode requested changes

2023-04-04 17:15 UTC, evan-goode commented on build/linux/desktop.template
> +MimeType=text/x-processing;x-scheme-handler/pde;
The `pde-handler.sh` script is not necessary, it looks like it is just unquoting the URL and passing it to the `processing` binary. Why not let `processing` handle the URLs itself? I don't think the unquoting is desirable in our case. These lines (1/2) should be all we need to get the `pde://` scheme working, I would take out the script.

This answer that Ben linked: https://unix.stackexchange.com/questions/497146/create-a-custom-url-protocol-handler/497147#497147 is about a slightly different use case.

2023-04-04 17:15 UTC, evan-goode commented on build/linux/install.sh
> +  xdg-mime default ${RESOURCE_NAME}.desktop x-scheme-handler/pde
(2/2)

2023-04-05 09:32 UTC, lala-lala-lori commented on build/linux/desktop.template
> +MimeType=text/x-processing;x-scheme-handler/pde;
Have tried with that?? and I don't think processing executable can handle url encoded path, and that %u it passed complete url include pde://

I tried `xdg-open pde://home/deidara/sketchbook/SimpleExport/SimpleExport.pde`
but not working the way you said.

Correct me if I'm wrong, I have tried your way but not working for me.

2023-04-06 01:22 UTC, evan-goode commented on build/linux/desktop.template
> +MimeType=text/x-processing;x-scheme-handler/pde;
It works for me, try with an extra `/` after the `pde://`: `xdg-open pde:///home/deidara/sketchbook/SimpleExport/SimpleExport.pde`. Oh, and it may need to be a `.pdez` or `.pdex` archive rather than a `.pde`. From reading the release notes it doesn't look like `.pde` files are supported: https://github.com/processing/processing4/releases/tag/processing-1292-4.2

The release notes mention a URL with 3 slashes, similar to `file:///`:
> Linking to pde://processing.org/somesketch.pdez in the browser will download somesketch.pdez and load it into the editor. It also works for files, for instance pde:///Users/ada/Desktop/somesketch.pdez will open an archive found on the Desktop.

This test page also works for me, see if it works for you: https://sableraf.github.io/testURIscheme/

Note: if Processing is not yet open and I run `xdg-open pde://sableraf.github.io/testURIscheme/sketchBundle.pdez`, it doesn't work and I see the following error in my terminal:
```
java.io.IOException: No such file or directory
	at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.base/java.io.File.createTempFile(File.java:2170)
	at processing.app.Base.openSketchBundle(Base.java:1217)
	at processing.app.Base.handleOpen(Base.java:1412)
	at processing.app.Base.<init>(Base.java:543)
	at processing.app.Base.createAndShowGUI(Base.java:286)
	at processing.app.Base.lambda$main$0(Base.java:130)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
If Processing is already open, it works fine. But I also see this error if I open a sketch from the command line, like `processing /path/to/sketch.pde`, so I don't think it is related to the `pde://` scheme handling.

2023-04-06 13:47 UTC, zriqo commented on build/linux/desktop.template
> +MimeType=text/x-processing;x-scheme-handler/pde;
ahh!, got yout point and my mistakes o7
I'll required make changes, thankss!

2023-04-06 14:54 UTC, closed without merging